<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE students[
<!ELEMENT students (student?)>
<!ELEMENT student (name?,age?,sex?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>]>

<students>
	<student>
		<name>张三</name>
		<age>21</age>
		<sex>男</sex>
	</student>
	

</students>